### PR TITLE
Fix for the renamed Marked 2 app

### PR DESCRIPTION
**Pull request by JMoVS**

### CODE REVIEW

**Comment by icio** [comment]
Hi, thank you for your submission. Apologies for taking so long to get back to you.

Your submission works fine for Marked 2, but I think I would prefer for it to work with Marked (1) when Marked 2 is not present. `subprocess.call` will return 1 if Marked 2 is not found which we can use to signal that we should try to launch in Marked 1 instead.

**Comment by icio** [comment]
I've submitted https://github.com/icio/sublime-text-marked/pull/5 which supersedes this pull request, but thank you again for your submission.

**Comment by JMoVS** [comment]
no problem, wasn't really long. I just discovered it and fixed it quick and dirty. You managed to make a far better version.
Will an updated version appear via package control?

**Comment by icio** [comment]
It will. If you tell package control to update it should show up instantly.

**Comment by JMoVS** [comment]
thx. Although sublime said there wasn't anything to upgrade, it upgraded it anyway as I figured out by now by looking at the code

**Pull request closed without merging**
